### ISSUE TITLE
Parsing string not file

### ISSUE THREAD

**Issue by 1970633640** [chireiden/python-ass#14]
Any functions to parse ass from string other than file? Sometimes it is hard or unnecessary to read from a file (e.g. Read ass file from a compressed file on the fly).

**Comment by FichteFoll** [comment]
Yes, you can do that.

```py
import ass

doc = ass.Document.parse_string(string)
# with the next release
doc = ass.parse_string(string)
```

I know the documentation isn't exactly complete currently, but I don't see myself working on that in the near future.

**Comment by FichteFoll** [comment]
Closing in favor of #9.
