### ISSUE TITLE
custom attributes present in "Format" in sections

### ISSUE THREAD

**Issue by pj-mathematician** [chireiden/python-ass#18]
I am dealing .ass files which have Event section like this:
```
[Events]
Format: Layer, Start, End, Style, Actor, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:01:50.64,0:01:54.42,Main03,Kondo,0,0,0,,Prisoner 3-2034.
```
and i want to access the `Actor` attribute, how do i do that?

**Comment by Ch0kehold** [comment]
That would likely be the name attribute.
In this case, for example, after you have parsed the file it would be `doc.events[0].name`.

**Comment by pj-mathematician** [comment]
that helps! thanks!
