### ISSUE TITLE
How can I add something to the ScriptInfoSection?

### ISSUE THREAD

**Issue by Askadelion** [chireiden/python-ass#20]
With doc.info[...] you can read the different infos.

But how can I add or change something to the current script if something is missing e.g. PlayResX: 640 to PlayResX: 720 or add ScaledBorderAndShadow if it is not present.

**Comment by FichteFoll** [comment]
```py
# intended usage
doc.info['PlayResX'] = 640
doc.info['ScaledBorderAndShadow'] = 'yes'
# backwards-compatibile aliases
doc.play_res_x = 640
doc.scaled_border_and_shadow = 'yes'
```
