### ISSUE TITLE
Can I merge the 'effect' column of more than 3 .ass files?

### ISSUE THREAD

**Issue by L-SSH** [chireiden/python-ass#8]
Hi, there :)

I am currently doing a transcription project, and there are three annotators to describe some certain features in the 'effect' column.
I'm wondering if it is possible that I can merge the text in the 'effect' column from the three annotators?

Thank you very much for your reply!  :)

**Comment by FichteFoll** [comment]
Could you provide an example for better understanding?

In theory, you can put anything you want into the effect field so long as it doesn't contain a comma.
